name: Python Verify

on:
  push:
    branches: [main, "feature/*", "fix/*", "dependabot/**"]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  verify:
    uses: ./.github/workflows/reusable-pyprojectx-verify.yml
